#!/bin/bash
set -e

login_user=`/usr/bin/stat -f%Su /dev/console`
qiwo_app_root="${DSTROOT}/Qiwo.app"
qiwo_executable="${qiwo_app_root}/Contents/MacOS/Qiwo"
rime_package_installer="${qiwo_app_root}/Contents/MacOS/rime-install"
rime_shared_data_path="${qiwo_app_root}/Contents/SharedSupport"

/usr/bin/sudo -u "${login_user}" /usr/bin/killall Qiwo > /dev/null || true

/usr/bin/sudo -u "${login_user}" "${qiwo_executable}" --register-input-source

if [ -z "${RIME_NO_PREBUILD}" ]; then
    pushd "${rime_shared_data_path}" > /dev/null
    "${qiwo_executable}" --build
    popd > /dev/null
fi && (
    /usr/bin/sudo -u "${login_user}" "${qiwo_executable}" --enable-input-source
    /usr/bin/sudo -u "${login_user}" "${qiwo_executable}" --select-input-source
)
